<<<<<<< Updated upstream
[2020-04-21 19:07:35,960]{/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/__init__.py:49} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/weather/q?city=Iceland&name=Andre&email=andrenovado@gmail.com&target_currency=EUR", "request": null, "response": ["Your destination temperature is 0.77 \u00b0 Celcius", {"ASIN": "B07682FRB1", "title": "Gildan Men's Ultra Cotton Adult Long Sleeve T-Shirt, 2-Pack, Dark Heather, X-Large", "price": "$11.99", "listPrice": "$14.50", "imageUrl": "https://m.media-amazon.com/images/I/51GidcpVbvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07682FRB1", "rating": "4.5", "totalReviews": "10615", "subtitle": "Gildan", "isPrimeEligible": "1", "converted_price": "11.04 EUR"}, {"ASIN": "B017YQL1X2", "title": "Wrangler Authentics Men's Authentics Fleece-Lined Cargo Pant, Anthracite Twill, 34W X 34L", "price": "$29.91", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41I+IxftPXL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B017YQL1X2", "rating": "4.6", "totalReviews": "3019", "subtitle": "Wrangler", "isPrimeEligible": "1", "converted_price": "27.53 EUR"}, {"ASIN": "B01N6IRDEU", "title": "iloveSIA Womens Hooded Coat Faux Fur Lined Jacket Black 12", "price": "$45.99", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41VTV1CFd3L._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B01N6IRDEU", "rating": "4.4", "totalReviews": "2481", "subtitle": "iloveSIA", "isPrimeEligible": "1", "converted_price": "42.33 EUR"}, {"ASIN": "B002YOMJSG", "title": "Timberland Men's White Ledge Mid Waterproof Ankle Boot,Black,10.5 M US", "price": "$74.96", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41w4ns963mL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B002YOMJSG", "rating": "4.4", "totalReviews": "1841", "subtitle": "", "isPrimeEligible": "1", "converted_price": "68.99 EUR"}, {"ASIN": "B07DJ5W3GQ", "title": "Amazon Essentials Men's 2-Pack Knit Beanie Hat, Navy/Gray Heather, One Size", "price": "$16.00", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/51fMaVEoAvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07DJ5W3GQ", "rating": "4.3", "totalReviews": "940", "subtitle": "", "isPrimeEligible": "1", "converted_price": "14.73 EUR"}]}
[2020-04-21 19:09:55,342]{/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/__init__.py:49} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/weather/q?city=oslo&name=Andre&email=andrenovado@gmail.com&target_currency=EUR", "request": null, "response": ["Your destination temperature is 8.35 \u00b0 Celcius", {"ASIN": "B07682FRB1", "title": "Gildan Men's Ultra Cotton Adult Long Sleeve T-Shirt, 2-Pack, Dark Heather, X-Large", "price": "$11.99", "listPrice": "$14.50", "imageUrl": "https://m.media-amazon.com/images/I/51GidcpVbvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07682FRB1", "rating": "4.5", "totalReviews": "10615", "subtitle": "Gildan", "isPrimeEligible": "1", "converted_price": "11.04 EUR"}, {"ASIN": "B017YQL1X2", "title": "Wrangler Authentics Men's Authentics Fleece-Lined Cargo Pant, Anthracite Twill, 34W X 34L", "price": "$29.91", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41I+IxftPXL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B017YQL1X2", "rating": "4.6", "totalReviews": "3019", "subtitle": "Wrangler", "isPrimeEligible": "1", "converted_price": "27.53 EUR"}, {"ASIN": "B01N6IRDEU", "title": "iloveSIA Womens Hooded Coat Faux Fur Lined Jacket Black 12", "price": "$45.99", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41VTV1CFd3L._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B01N6IRDEU", "rating": "4.4", "totalReviews": "2481", "subtitle": "iloveSIA", "isPrimeEligible": "1", "converted_price": "42.33 EUR"}, {"ASIN": "B002YOMJSG", "title": "Timberland Men's White Ledge Mid Waterproof Ankle Boot,Black,10.5 M US", "price": "$74.96", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41w4ns963mL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B002YOMJSG", "rating": "4.4", "totalReviews": "1841", "subtitle": "", "isPrimeEligible": "1", "converted_price": "68.99 EUR"}, {"ASIN": "B07DJ5W3GQ", "title": "Amazon Essentials Men's 2-Pack Knit Beanie Hat, Navy/Gray Heather, One Size", "price": "$16.00", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/51fMaVEoAvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07DJ5W3GQ", "rating": "4.3", "totalReviews": "940", "subtitle": "", "isPrimeEligible": "1", "converted_price": "14.73 EUR"}]}
[2020-04-21 19:13:40,197]{/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/__init__.py:49} WARNING - REQUEST_LOG	{"method": "GET", "code": "200 OK", "uri": "/weather/q?city=glasgow&name=Andre&email=andrenovado@gmail.com&target_currency=GBP", "request": null, "response": ["Your destination temperature is 3.74 \u00b0 Celcius", {"ASIN": "B07682FRB1", "title": "Gildan Men's Ultra Cotton Adult Long Sleeve T-Shirt, 2-Pack, Dark Heather, X-Large", "price": "$11.99", "listPrice": "$14.50", "imageUrl": "https://m.media-amazon.com/images/I/51GidcpVbvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07682FRB1", "rating": "4.5", "totalReviews": "10615", "subtitle": "Gildan", "isPrimeEligible": "1", "converted_price": "9.64 GBP"}, {"ASIN": "B017YQL1X2", "title": "Wrangler Authentics Men's Authentics Fleece-Lined Cargo Pant, Anthracite Twill, 34W X 34L", "price": "$29.91", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41I+IxftPXL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B017YQL1X2", "rating": "4.6", "totalReviews": "3019", "subtitle": "Wrangler", "isPrimeEligible": "1", "converted_price": "24.04 GBP"}, {"ASIN": "B01N6IRDEU", "title": "iloveSIA Womens Hooded Coat Faux Fur Lined Jacket Black 12", "price": "$45.99", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41VTV1CFd3L._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B01N6IRDEU", "rating": "4.4", "totalReviews": "2481", "subtitle": "iloveSIA", "isPrimeEligible": "1", "converted_price": "36.96 GBP"}, {"ASIN": "B002YOMJSG", "title": "Timberland Men's White Ledge Mid Waterproof Ankle Boot,Black,10.5 M US", "price": "$74.96", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/41w4ns963mL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B002YOMJSG", "rating": "4.4", "totalReviews": "1841", "subtitle": "", "isPrimeEligible": "1", "converted_price": "60.25 GBP"}, {"ASIN": "B07DJ5W3GQ", "title": "Amazon Essentials Men's 2-Pack Knit Beanie Hat, Navy/Gray Heather, One Size", "price": "$16.00", "listPrice": "", "imageUrl": "https://m.media-amazon.com/images/I/51fMaVEoAvL._SL160_.jpg", "detailPageURL": "https://www.amazon.com/dp/B07DJ5W3GQ", "rating": "4.3", "totalReviews": "940", "subtitle": "", "isPrimeEligible": "1", "converted_price": "12.86 GBP"}]}
[2020-04-21 19:21:06,666]{/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /weather/q [GET]
Traceback (most recent call last):
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/.virtualenvs/rest_training/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/weather/resources.py", line 31, in get
    shirt = GetPriceReport().get('shirt for winter')
  File "/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/amazon/resources.py", line 35, in get
    converted_price = GetConversion().get(result_product['price'])
  File "/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/conversion/resources.py", line 31, in get
    price = float((re.findall("[0-9]+,?.?[0-9]+", product_price))[0].replace(',','.'))
IndexError: list index out of range
[2020-04-21 19:21:06,668]{/home/andrenovado/Documents/Coding/Alterra/andre_derby_restful_api/blueprints/__init__.py:59} ERROR - REQUEST_LOG	{"method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/weather/q?city=moscow&name=Andre&email=andrenovado@gmail.com&target_currency=GBP", "request": null, "response": {"message": "Internal Server Error"}}
=======
[2020-04-21 18:45:14,859]{/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask/app.py:1892} ERROR - Exception on /client [POST]
Traceback (most recent call last):
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'status' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta8/Documents/RESTAPI/andre_derby_restful_api/blueprints/client/resources.py", line 77, in post
    db.session.commit()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/alta8/Documents/virtualenv/project_restapi/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'status' at row 1")
[SQL: INSERT INTO client (client_key, client_secret, salt, status, updated_at, deleted_at) VALUES (%(client_key)s, %(client_secret)s, %(salt)s, %(status)s, %(updated_at)s, %(deleted_at)s)]
[parameters: {'client_key': 'internal', 'client_secret': '4c7b8196afde81576f61e4d5e50c203ca03985c857fb681e25519fb9550b40da21f7f5a8b963a83bc999b666371c048556c7ac4b33a93aecec17c382666dbd01', 'salt': 'True', 'status': '6c8f1f05ecdc4f208fb5230cfc5ff6bd', 'updated_at': None, 'deleted_at': None}]
(Background on this error at: http://sqlalche.me/e/9h9h)
[2020-04-21 18:45:14,879]{/home/alta8/Documents/RESTAPI/andre_derby_restful_api/blueprints/__init__.py:65} ERROR - REQUEST_LOG	{"method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/client?", "request": {"client_key": "internal", "client_secret": "super_secret_client", "status": "True"}, "response": {"message": "Internal Server Error"}}
[2020-04-21 18:46:45,862]{/home/alta8/Documents/RESTAPI/andre_derby_restful_api/blueprints/__init__.py:55} WARNING - REQUEST_LOG	{"method": "POST", "code": "200 OK", "uri": "/client?", "request": {"client_key": "internal", "client_secret": "super_secret_client", "status": "True"}, "response": {"id": 1, "client_key": "internal", "client_secret": "4a0c0513007f2616ef99f4bf95fa2c538088b6e94e189151a5a2bf376d9c8dd4a26f9c50cc84d02b7e563890fa8bf5dadb3ab0977f57c92a7f428fa48d899641", "salt": "25be89a5b9f545ae8b47c4d478b6ce27", "status": "True", "created_at": "Tue, 21 Apr 2020 18:46:45 -0000", "updated_at": null, "deleted_at": null}}
>>>>>>> Stashed changes
